site_name: BigQuery Public Data
site_url: http://localhost:8000
extra_css:
  - style.css
theme:
  name: material
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.prune
    - navigation.indexes     
markdown_extensions:
  - attr_list
  - md_in_html  
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
